image: ruby:2.3
before_script:
  - gem install bundler
test:
  stage: test
  script:
  - bundle install --path=vendor/
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master
pages:
  stage: deploy
  script:
  - bundle install --path=vendor/
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
