image: ruby:2.3
test:
  stage: test
  script:
  - gem install bundler jekyll jekyll-feed jekyll-paginate pygments.rb redcarpet
  - jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master
pages:
  stage: deploy
  script:
  - gem install bundler jekyll jekyll-feed jekyll-paginate pygments.rb redcarpet
  - jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
